[package]
name = "rust-life"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
rand = "0.8.5"
crossterm = "0.28.1"
ctrlc = "3.4.5"
rustc-hash = "2.1.0"
anyhow = "1.0.97"
lazy_static = "1.5.0"
serial_test = "3.2.0"
